import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import { Oswald } from 'next/font/google';

const bebasNeue = Oswald({
  weight: '400', // or use '700' for bold
  subsets: ['latin'], // You can specify other subsets like 'latin-ext' if needed
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${bebasNeue.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
